# Generated by Django 5.0.7 on 2024-08-03 06:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('selected', models.BooleanField(default=False)),
                ('label_size_mm', models.FloatField(default=25)),
                ('num_label_in_row', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Initial', 'Initial'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Error', 'Error')], default='Initial', help_text='QR code type', max_length=20)),
                ('used_rows', models.IntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('file_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
