# Generated by Django 5.0.7 on 2024-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printertaskmodel',
            name='task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='printertaskmodel',
            name='status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Error', 'Error')], default='Initial', help_text='Printer task status', max_length=20),
        ),
    ]
