# Generated by Django 5.0.7 on 2024-08-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printerapp', '0002_printertaskmodel_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printermodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
